version: '3.4'

services:
  catalogdb:
    image: mongo:4.4

  basketdb:
    image: redis:alpine
    
  discountdb:
    image: postgres

  portainer:
    image: portainer/portainer-ce

  dolcecuore.services.basket.api:
    image: ${DOCKER_REGISTRY-}dolcecuoreservicesbasketapi
    build:
      context: .
      dockerfile: Services.Basket/Dolcecuore.Services.Basket.Api/Dockerfile

  dolcecuore.services.catalog.api:
    image: ${DOCKER_REGISTRY-}dolcecuoreservicescatalogapi
    build:
      context: .
      dockerfile: Services.Catalog/Dolcecuore.Services.Catalog.Api/Dockerfile
      
  dolcecuore.services.discount.api:
    image: ${DOCKER_REGISTRY-}dolcecuoreservicesdiscountapi
    build:
      context: .
      dockerfile: Services.Discount/Dolcecuore.Services.Discount.Api/Dockerfile
      
  dolcecuore.services.discount.grpc:
    image: ${DOCKER_REGISTRY-}dolcecuoreservicesdiscountgrpc
    build:
      context: .
      dockerfile: Services.Discount/Dolcecuore.Services.Discount.Grpc/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data: