version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  basketdb: 
    container_name: basketdb
    restart: always
    ports:
        - "6379:6379"
          
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  orderdb:
    container_name: orderdb
    environment:
      - SA_PASSWORD=password
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1433:1433"

  dolcecuore.services.catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Mongo__ConnectionString=mongodb://catalogdb:27017
    depends_on:
      - catalogdb
    ports:
      - "8001:80"

  dolcecuore.services.basket.api:
    container_name: basket.api
    environment:
      - Redis__ConnectionString=basketdb:6379
      - ASPNETCORE_ENVIRONMENT=Development
      - Grpc__DiscountUrl=http://dolcecuore.services.discount.grpc
    depends_on:
        - basketdb
    ports:
      - "8002:80"

  dolcecuore.services.discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Postgres__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin
    depends_on:
      - discountdb
    ports:
      - "8003:80"

  dolcecuore.services.discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Postgres__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin
    depends_on:
      - discountdb
    ports:
      - "8004:80"
        
  dolcecuore.services.order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=password
    depends_on:
      - orderdb
    ports:
      - "8005:80"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
        
  portainer :
    container_name : portainer
    restart : always
    ports :
      - "8080:8000"
      - "9000:9000"
    volumes :
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
