version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest

  basketdb:
    image: redis:alpine
    
  discountdb:
    image: postgres

  dolcecuore.services.basket.api:
    image: ${DOCKER_REGISTRY-}dolcecuoreservicesbasketapi
    build:
      context: .
      dockerfile: Services.Basket/Dolcecuore.Services.Basket.Api/Dockerfile

  dolcecuore.services.catalog.api:
    image: ${DOCKER_REGISTRY-}dolcecuoreservicescatalogapi
    build:
      context: .
      dockerfile: Services.Catalog/Dolcecuore.Services.Catalog.Api/Dockerfile
      
  dolcecuore.services.discount.api:
    image: ${DOCKER_REGISTRY-}dolcecuoreservicesdiscountapi
    build:
      context: .
      dockerfile: Services.Discount/Dolcecuore.Services.Discount.Api/Dockerfile
      
  dolcecuore.services.discount.grpc:
    image: ${DOCKER_REGISTRY-}dolcecuoreservicesdiscountgrpc
    build:
      context: .
      dockerfile: Services.Discount/Dolcecuore.Services.Discount.Grpc/Dockerfile
      
  dolcecuore.services.order.api:
    image: ${DOCKER_REGISTRY-}dolcecuoreservicesorderapi
    build:
      context: .
      dockerfile: Services.Order/Dolcecuore.Services.Order.Api/Dockerfile
      
  dolcecuore.gateways.webapi:
    image: ${DOCKER_REGISTRY-}dolcecuoregatewayswebapi
    build:
      context: .
      dockerfile: Gateways.WebAPI/Dockerfile
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  portainer :
    image : portainer/portainer-ce

volumes:
  mongo_data:
  portainer_data:
  postgres_data: