version: '3.4'

services:
  mssql:
    container_name: mssql
    restart: always
    ports:
        - "1433:1433"
    environment :
      SA_PASSWORD : "sqladmin123!@#"
      MSSQL_PID : "Developer"
      ACCEPT_EULA : "Y"

  basketdb: 
    container_name: basketdb
    restart: always
    ports:
        - "6379:6379"
          
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dolcecuore.services.catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Dolcecuore=Server=mssql;Database=Dolcecuore.Microservices.Catalog;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true
      - MessageBroker__Provider=RabbitMQ
      - MessageBroker__RabbitMQ__HostName=rabbitmq
    depends_on:
      - mssql
    ports:
      - "8001:80"

  dolcecuore.services.basket.api:
    container_name: basket.api
    environment:
      - Redis__ConnectionString=basketdb:6379
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Dolcecuore=Server=mssql;Database=Dolcecuore.Microservices.BasketEvents;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true
      - Services__Grpc__Discount=http://dolcecuore.services.discount.grpc
      - MessageBroker__Provider=RabbitMQ
      - MessageBroker__RabbitMQ__HostName=rabbitmq
      - Caching__Distributed__Provider=Redis
      - Caching__Distributed__Redis__Configuration=basketdb:6379
    depends_on:
        - basketdb
        - mssql
        - dolcecuore.services.order.api
        - dolcecuore.services.discount.grpc
    ports:
      - "8002:80"

  dolcecuore.services.discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Postgres__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin
    depends_on:
      - discountdb
    ports:
      - "8003:80"

  dolcecuore.services.discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Postgres__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin
    depends_on:
      - discountdb
    ports:
      - "8004:80"
        
  dolcecuore.services.order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Dolcecuore=Server=mssql;Database=Dolcecuore.Microservices.Orders;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true
      - MessageBroker__Provider=RabbitMQ
      - MessageBroker__RabbitMQ__HostName=rabbitmq
    depends_on:
      - mssql
    ports:
      - "8005:80"
        
  dolcecuore.gateways.webapi:
    container_name: webapi
    environment :
      - ASPNETCORE_ENVIRONMENT=Development
      - Ocelot__DefaultDownstreamScheme="http"
      - Ocelot__Routes__Catalog__Downstream="http://catalog.api"
      - Ocelot__Routes__Basket__Downstream="http://basket.api"
      - Ocelot__Routes__Discount__Downstream="http://discount.api"
      - Ocelot__Routes__Order__Downstream="http://order.api"
    ports :
      - "9002:80"
    depends_on :
      - db

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
        
  portainer :
    container_name : portainer
    restart : always
    ports :
      - "8080:8000"
      - "9000:9000"
    volumes :
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
