version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  basketdb: 
    container_name: basketdb
    restart: always
    ports:
        - "6379:6379"
          
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASWWORD=admin
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  portainer: 
    container_name: portainer
    restart: always
    ports:
        - "8080:8000"
        - "9000:9000"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

  dolcecuore.services.catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Database:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  dolcecuore.services.basket.api:
    container_name: basket.api
    environment:
      - "Redis:ConnectionString=localhost:6379"
      - ASPNETCORE_ENVIRONMENT=Development
      - "Grpc:DiscountUrl=discount.grpc"
    depends_on:
        - basketdb
    ports:
      - "8001:80"

  dolcecuore.services.discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Server=localhost;Port=5432;Database=DiscountDb;User Id=admin;Password=admin"
    depends_on:
      - discountdb
    ports:
      - "8002:80"

  dolcecuore.services.discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Server=localhost;Port=5432;Database=DiscountDb;User Id=admin;Password=admin"
    depends_on:
      - discountdb
    ports:
      - "8003:80"